# Generated by Django 6.1.1 on 2026-10-05 10:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60)),
                ('target', models.CharField(max_length=200)),
                ('detail', models.TextField(blank=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('office', models.CharField(choices=[('UK', 'United Kingdom'), ('IN', 'India')], max_length=2)),
            ],
            options={
                'ordering': ['office', 'name'],
                'unique_together': {('name', 'office')},
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=20, unique=True, verbose_name='Employee ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('office', models.CharField(choices=[('UK', 'United Kingdom'), ('IN', 'India')], max_length=2)),
                ('role', models.CharField(choices=[('employee', 'Employee'), ('team_lead', 'Team lead'), ('admin', 'Admin')], default='employee', max_length=20)),
                ('business_unit', models.CharField(blank=True, help_text='e.g. Calicut', max_length=100)),
                ('date_joined', models.DateField()),
                ('probation_end_date', models.DateField(blank=True, null=True)),
                ('date_left', models.DateField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('uan', models.CharField(blank=True, max_length=20, verbose_name='UAN number')),
                ('pan', models.CharField(blank=True, max_length=10, verbose_name='PAN number')),
                ('esic_ip_number', models.CharField(blank=True, max_length=20, verbose_name='ESIC insurance number')),
                ('aadhaar_last4', models.CharField(blank=True, help_text='Never store the full Aadhaar number.', max_length=4, verbose_name='Aadhaar (last 4 digits only)')),
                ('pf_enrolled', models.BooleanField(default=False, verbose_name='Enrolled in PF')),
                ('esic_enrolled', models.BooleanField(default=False, verbose_name='Enrolled in ESIC')),
                ('opening_leave_balance', models.DecimalField(decimal_places=1, default=Decimal('0'), help_text='Balance before the first payslip in this system.', max_digits=5, verbose_name='Paid leave balance at go-live')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.department')),
                ('team_lead', models.ForeignKey(blank=True, help_text="Approves this person's leave.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='hr.employee')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['office', 'employee_code'],
            },
        ),
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_given', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_recovery', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='hr.employee')),
            ],
            options={
                'ordering': ['-date_given'],
            },
        ),
        migrations.CreateModel(
            name='EmploymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('designation', models.CharField(max_length=100)),
                ('weekly_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('basic_monthly', models.DecimalField(blank=True, decimal_places=2, help_text='India staff only. UK salaries are not stored in this system.', max_digits=12, null=True, verbose_name='Monthly Basic (INR)')),
                ('reason', models.CharField(blank=True, help_text='e.g. Joined, Promotion, Annual increment', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_records', to='hr.employee')),
            ],
            options={
                'ordering': ['-effective_from', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days', models.DecimalField(decimal_places=1, help_text='Use .5 for half days.', max_digits=4)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='hr.employee')),
            ],
            options={
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Needs admin input'), ('ready', 'Ready for approval'), ('approved', 'Approved'), ('published', 'Published'), ('superseded', 'Superseded')], default='draft', max_length=12)),
                ('employee_code', models.CharField(max_length=20)),
                ('employee_name', models.CharField(max_length=150)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('business_unit', models.CharField(blank=True, max_length=100)),
                ('uan', models.CharField(blank=True, max_length=20)),
                ('pan', models.CharField(blank=True, max_length=10)),
                ('esic_ip_number', models.CharField(blank=True, max_length=20)),
                ('aadhaar_last4', models.CharField(blank=True, max_length=4)),
                ('basic', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pf_applies', models.BooleanField(default=False)),
                ('esic_applies', models.BooleanField(default=False)),
                ('leave_taken', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=5)),
                ('paid_leave_applied', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=5)),
                ('days_not_employed', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=5)),
                ('leave_balance_before', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=5)),
                ('leave_accrued', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=5)),
                ('leave_balance_after', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=5)),
                ('bonus', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('incentives', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('overtime', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('other_additions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('other_deductions_note', models.CharField(blank=True, max_length=200)),
                ('advance_recovery', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('admin_note', models.CharField(blank=True, max_length=300)),
                ('lop_days', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=5)),
                ('lop_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('pf_employee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('pf_employer', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('esic_employee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('esic_employer', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('employer_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='hr.employee')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='hr.payrollrun')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='hr.payslip')),
            ],
            options={
                'ordering': ['employee_code', '-version'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('must_change_password', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hr_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
