# Generated by Django 6.1.1 on 2026-10-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentrecord',
            name='annual_salary_gbp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='UK staff only. Visible to admins only.', max_digits=12, null=True, verbose_name='Annual salary (GBP)'),
        ),
        migrations.AlterField(
            model_name='employmentrecord',
            name='basic_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='India staff only.', max_digits=12, null=True, verbose_name='Monthly Basic (INR)'),
        ),
    ]
