# Generated by Django 6.1.1 on 2026-10-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_uk_annual_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_joined',
            field=models.DateField(blank=True, null=True),
        ),
    ]
